extends Node

var ATTACH_TO_CEILING = "ATTACH_TO_CEILING"
var ATTACH_TO_FLOOR = "ATTACH_TO_FLOOR"
var ATTACH_TO_LEFT_WALL = "ATTACH_TO_LEFT_WALL"
var ATTACH_TO_RIGHT_WALL = "ATTACH_TO_RIGHT_WALL"
var LAND = "LAND"
var JUMP = "JUMP"
var FALL = "FALL"
var RELEASE = "RELEASE"
